# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApexClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=18)),
                ('name', models.CharField(max_length=80)),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApexClassElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Method', 'Method'), ('Property', 'Property'), ('Variable', 'Variable')], max_length=20)),
                ('name', models.CharField(max_length=80)),
                ('apex_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codescanner.ApexClass')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=40, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_date', models.DateTimeField(blank=True, null=True)),
                ('org_id', models.CharField(max_length=18)),
                ('username', models.CharField(blank=True, max_length=80, null=True)),
                ('access_token', models.CharField(max_length=255)),
                ('instance_url', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('Processing', 'Processing'), ('Finished', 'Finished'), ('Error', 'Error')], default='Not Started', max_length=40)),
                ('error', models.TextField(blank=True, null=True)),
                ('stack_trace', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='apexclass',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codescanner.Job'),
        ),
    ]
