# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codescanner', '0005_auto_20171124_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='apexclass',
            name='symbol_table_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
