# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codescanner', '0006_apexclass_symbol_table_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='apexclass',
            name='class_member_id',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
