# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codescanner', '0007_apexclass_class_member_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apexclasselement',
            name='apex_class',
        ),
        migrations.DeleteModel(
            name='ApexClassElement',
        ),
    ]
