# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codescanner', '0008_auto_20171125_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='apexclass',
            name='is_referenced_externally',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apexclass',
            name='referenced_by_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
