# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codescanner', '0009_auto_20171127_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApexPageComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf_id', models.CharField(max_length=18)),
                ('name', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('type', models.CharField(default='Page', max_length=10)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codescanner.Job')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
