# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codescanner', '0010_apexpagecomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='apexpagecomponent',
            name='controller',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
