# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codescanner', '0011_apexpagecomponent_controller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apexclass',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='apexpagecomponent',
            name='controller',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='apexpagecomponent',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='job',
            name='username',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
